export const light = {
    body: '#EAEEF6',
    orangeText: '#FF6D00',
    orangeBg: '#FFE4C2',
    greenText: '#06B16E',
    greenBg: '#B4FDD1',
    purpleText: '#9A48F1',
    purpleBg: '#E9D4FF',
    grayText: '#FFFFFF',
    grayBg: '#94A6BE',
    cardBg: '#FFFFFF',
    cardTtl: '#000000',
    headerBg: '#FFFFFF',
    userNameClr: '#565EEF',
    popUserSetBg: '#FFFFFF',
    popUserSetBorder: '#94A6BE66',
    popUserSetShadow: '#1A386536',
    popUserSetText: '#000000',
    checkboxBg: '#EAEEF6',
    checkboxToggle: '#94A6BE',
    popUserSetBtn: '#565EEF',
    LoginBlockBorder: '#D4DBE5',
}

export const dark = {
    body: '#151419',
    orangeText: '#FFE4C2',
    orangeBg: '#FF6D00',
    greenText: '#B4FDD1',
    greenBg: '#06B16E',
    purpleText: '#E9D4FF',
    purpleBg: '#9A48F1',
    grayText: '#94A6BE',
    grayBg: '#FFFFFF',
    cardBg: '#20202C',
    cardTtl: '#FFFFFF',
    headerBg: '#20202C',
    userNameClr: '#FFFFFF',
    popUserSetBg: '#202229',
    popUserSetBorder: '#4E5566',
    popUserSetShadow: '#94A6BE66',
    popUserSetText: '#FFFFFF',
    checkboxBg: '#FFFFFF',
    checkboxToggle: '#565EEF',
    popUserSetBtn: '#FFFFFF',
    LoginBlockBorder: '#4E5566',
}
